name: auoms
on:
  [workflow_dispatch]
   
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, ubuntu-22.04] 
    steps:
      - name: print2
        run: sudo systemctl status auoms
